// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shop_project/features/auth/domain/email/entity/email_identity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EmailIdentityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EmailIdentityAdapter());
  }
}
